### ISSUE TITLE
Dude you have a backdoor script

### ISSUE THREAD

**Issue by JasonShin** [indexzero/ps-tree#36]
Check this

https://github.com/dominictarr/event-stream/issues/115

I'm uninstalling all the modules in relation to this until the issue is resolved ...

**Comment by wkillerud** [comment]
@JasonShin this has been reported and fixed already #33 #34

**Comment by indexzero** [comment]
Yes @wkillerud is correct. This was fixed in `ps-tree@1.1.1` and you can force upgrade to it by regenerating your `node_modules` and `package-lock.json`/`yarn.lock` files. 

Unfortunately due to how the `npm` registry works I cannot unpublish older versions of `ps-tree` so copies of `ps-tree@1.1.0` could still potentially be installed from older `package-lock.json` or `yarn.lock` files.
